### ISSUE TITLE
Missing interface items required for go-spacemesh integration

### ISSUE THREAD

**Issue by lrettig** [athenavm/athena#127]
The first two (max spend, verify) are the most critical. The others are either only used in tests, or we can otherwise mock them for now.

- [ ] #128: max spend for tx (target template, payload) -> uint64
- [ ] #129: verify for (principal, payload) -> bool
- [ ] #131: encode spend tx payload for (recipient, amount) -> []byte; spawn tx payload for (template, owner pubkey) -> []byte
- [ ] nonce for (target template, payload) -> uint64
- [ ] BaseGas, LoadGas, ExecGas for (target template, payload) -> uint64
- [ ] ~#130: calculate principal address for (principal template, payload) -> Address~

See https://github.com/spacemeshos/go-spacemesh/pull/6180#issuecomment-2398164403 and https://spacemesh.slack.com/archives/C060PGXV27M/p1728347183591949
